name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: List .next directory
        run: ls -la .next

      - name: List .next export
        run: ls -la .next/export

      - name: List .next static
        run: ls -la .next/static

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .next/static

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
