# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Node.js CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    pull_requests:
      branches: ["master"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
  straategy:
    matrix:
      node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build 
        run:yarn && yarn build && yarn export
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy
          CLEAN: true # Automatically remove deleted files from the gh-pages branch
